// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzFHaKD1gy1zQURbwlOP3Kt4p30ULD87w',
    appId: '1:819828956856:web:5fe841ffb5fa08d4df9e4d',
    messagingSenderId: '819828956856',
    projectId: 'authtutorial-1868c',
    authDomain: 'authtutorial-1868c.firebaseapp.com',
    storageBucket: 'authtutorial-1868c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsez5IeidhPQk2FFdcWAC1Fz36rWYfpoQ',
    appId: '1:819828956856:android:57c7782dff6ed363df9e4d',
    messagingSenderId: '819828956856',
    projectId: 'authtutorial-1868c',
    storageBucket: 'authtutorial-1868c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWrBrqlYB99ER1DteNSzFW80lCekgQaRo',
    appId: '1:819828956856:ios:af9eb0b5aae72828df9e4d',
    messagingSenderId: '819828956856',
    projectId: 'authtutorial-1868c',
    storageBucket: 'authtutorial-1868c.appspot.com',
    iosBundleId: 'com.example.authPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWrBrqlYB99ER1DteNSzFW80lCekgQaRo',
    appId: '1:819828956856:ios:e878c5581a807e76df9e4d',
    messagingSenderId: '819828956856',
    projectId: 'authtutorial-1868c',
    storageBucket: 'authtutorial-1868c.appspot.com',
    iosBundleId: 'com.example.authPage.RunnerTests',
  );
}
